name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    
    runs-on: ubuntu-latest

    
    steps:
    
      - uses: actions/checkout@v2

    
      - name: UnitTest
        run: python3 -m unittest



